name: Publish Package

on:
  push:
    branches: [ main ]
    paths:
      - 'SickRfid/*'
      - 'Directory.Build.props'
      - '.github/workflows/PUBLISH_PACKAGE.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish SickRfidController to NuGet
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: SickRfid/SickRfid.csproj
          NUGET_KEY: ${{secrets.PUBLISH_TO_NUGET_ORG}}